//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceClients
    {
        public int ID { get; set; }
        public string Service { get; set; }
        public string date_start { get; set; }
        public string Surname { get; set; }
    
        public virtual Clients Clients { get; set; }
    }
}
